version: "3.7"

services:

  taskmanager:
    build: ./taskmanager
    container_name: taskmanager
    restart: always
    volumes:
      - .:/code
    ports:
      - "9033:9033"

  client:
    build: ./client
    container_name: client
    restart: always
    expose:
      - 9034

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

#  mysql:
#    image: mysql:5.7
#    ports:
#      - "32000:3306"
#    environment:
#      MYSQL_DATABASE: test
#      MYSQL_ROOT_HOST: 0.0.0.0
#      MYSQL_USER: testing
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_PASSWORD: admin


